name: diu_transport_driver_app
description: "Driver app for DIU Transport System"
publish_to: 'none'

version: 1.0.0-beta+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  maplibre_gl: ^0.21.0
  http: ^1.4.0
  socket_io_client: ^3.0.2
  flutter_dotenv: ^5.2.1
  path: ^1.9.1
  mobile_scanner: ^7.0.1
  connectivity_plus: ^6.1.4
  geolocator: ^14.0.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.1.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/icons/
