name: diu_transport_student_app
description: "Student app for DIU Transport System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  maplibre_gl: ^0.21.0
  http: ^1.0.0
  socket_io_client: ^3.0.2
  flutter_dotenv: ^5.2.1
  path: ^1.9.1
  google_fonts: ^6.2.1
  url_launcher: ^6.1.7
  shared_preferences: ^2.0.13
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/image/
    - assets/.env
